#!/bin/bash
#all dotfiles that go in ~
for dotfile in .*; do
    if [ -f $dotfile ]; then
        if [ -f ~/$dotfile ]; then
            rm -f ~/$dotfile
        fi
        ln -s $PWD/$dotfile ~/$dotfile
    fi
done

./ssh/setup
