#!/bin/bash
#all dotfiles that go in ~
script_directory=`dirname "$0"`
for dotfile in $script_directory/.*; do
    if [ -f $dotfile ]; then
        symlink $dotfile ~/$dotfile
    fi
done

#ssh
./$script_directory/ssh/setup
